
const APP_DATA_DIRECTORY = process.env.APPDATA || (process.platform == 'darwin' ? process.env.HOME + '/Library/Preferences' : process.env.HOME + "/.local/share");
const WORKING_DIRECTORY = APP_DATA_DIRECTORY+"/robot-data";
const ROBOTS_DIRECTORY = WORKING_DIRECTORY + "/robots";
const DOWNLOAD_ROBOT_COMMAND = "DOWNLOAD_ROBOT";
const DOWNLOAD_ROBOT_COMMAND_REPLY = "DOWNLOAD_ROBOT_REPLY";
const EXECUTE_ROBOT_COMMAND = "EXECUTE_ROBOT";
const EXECUTE_ROBOT_COMMAND_REPLY = "EXECUTE_ROBOT_REPLY";
const SQLITE_PATH = WORKING_DIRECTORY+"/robo.db";
const SEPARATOR ="(#__#)";
const EXECUTE_COMMAND_FROM_MAIN = "EXECUTE_COMMAND_FROM_MAIN";
const EXECUTE_COMMAND_FROM_MAIN_REPLY = "EXECUTE_COMMAND_FROM_MAIN_REPLY";
const UPDATE_OUTPUT_DIRECTORY_COMMAND = "UPDATE_OUTPUT_DIRECOTRY";
const DEFAULT_OUTPUT_DIRECTORY = WORKING_DIRECTORY+"/output";
const OPEN_DIRETORY_COMMAND = "OPEN_DIRECTORY";
const FETCH_ROBOTS_COMMAND = "FETCH_ROBOTS_COMMAND";
const FETCH_ROBOTS_COMMAND_REPLY = "FETCH_ROBOTS_COMMAND_REPLY";

const FETCH_REMOTE_ROBOTS_COMMAND = "FETCH_SUPABASE_ROBOTS_COMMAND";
const FETCH_REMOTE_ROBOTS_COMMAND_REPLY = "FETCH_SUPABASE_ROBOTS_COMMAND_REPLY";

const DELETE_ROBOT_COMMAND = "DELETE_ROBOT";
const DELETE_ROBOT_COMMAND_REPLY = "DELETE_ROBOT_REPLY";

const   SUPABASE_URL = "https://bbtvdrdympizfodqmvzu.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidHZkcmR5bXBpemZvZHFtdnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDAwNzY2NzQsImV4cCI6MjAxNTY1MjY3NH0.zYRRp5BMX-0oPWVacLpC5dB57TM1k2_68Z9TX7fVEsw";


module.exports = {
  SEPARATOR,
  EXECUTE_COMMAND_FROM_MAIN,
  WORKING_DIRECTORY,
  ROBOTS_DIRECTORY,
  DOWNLOAD_ROBOT_COMMAND,
  EXECUTE_ROBOT_COMMAND,
  EXECUTE_ROBOT_COMMAND_REPLY,
  SQLITE_PATH,EXECUTE_COMMAND_FROM_MAIN_REPLY,
  UPDATE_OUTPUT_DIRECTORY_COMMAND,
  DEFAULT_OUTPUT_DIRECTORY,
  APP_DATA_DIRECTORY,
  OPEN_DIRETORY_COMMAND,
  FETCH_ROBOTS_COMMAND,
  FETCH_ROBOTS_COMMAND_REPLY,
  DELETE_ROBOT_COMMAND,
  DELETE_ROBOT_COMMAND_REPLY,
  DOWNLOAD_ROBOT_COMMAND_REPLY,
  SUPABASE_KEY,
  SUPABASE_URL,
FETCH_REMOTE_ROBOTS_COMMAND,
FETCH_REMOTE_ROBOTS_COMMAND_REPLY

};
